const messageUtil = {
  OK: 'OK',
  EMPTY_FIELD: 'Please Enter',
  ALL_READY_EXIST: 'Record Already Exist',
  USER_CREATED: 'User Created Successfully',
  CLUB_CREATED: 'Club Created Successfully',
  RECORD_NOT_CREATED: 'Record Not Created',
  NOT_FOUND: 'Record Not Found',
  EMAIL_SENT: 'Email Sent Successfully',
  CLUB_OWNER_NOT_FOUND: 'Club Owner Not Found',
  CLUB_NOT_FOUND: 'Club Not Found',
  INCORRECT_PASSWORD: 'Incorrect Password',
  LOGIN_SUCCESS: 'Login Successfully',
  UNAUTHORIZED: 'User not authorized',
  REQUIRED_USER_ID: 'User ID is required',
  UPDATE: 'Data is successfully updated',
  FILENOTUPLOADED: 'File Not Uploaded',
  NAME_STRING_BASE: " Name should be a type of 'text'",
  NAME_STRING_EMPTY: ' Name cannot be an empty field',
  NAME_REQUIRED: 'Name is required',
  LASTNAME_STRING_BASE: "Last name should be a type of 'text'",
  LASTNAME_STRING_EMPTY: 'Last Name cannot be an empty field',
  LASTNAME_REQUIRED: 'Last Name is required',
  ROLE_STRING_BASE: "Role should be a type of 'text'",
  ROLE_STRING_EMPTY: 'Role cannot be an empty field',
  ROLE_REQUIRED: 'Role is required',
  CITY_STRING_BASE: "City should be a type of 'text'",
  CITY_STRING_EMPTY: 'City cannot be an empty field',
  CITY_REQUIRED: 'City is required',
  EMAIL_STRING_BASE: "Email should be a type of 'text'",
  EMAIL_STRING_EMPTY: 'Email cannot be an empty field',
  EMAIL_REQUIRED: 'Email is required',
  EMAIL_NOT_VALID: 'Email is not valid',
  PASSWORD_STRING_BASE: "Password should be a type of 'text'",
  PASSWORD_STRING_EMPTY: 'Password cannot be an empty field',
  PASSWORD_REQUIRED: 'Password is required',
  REGISTER_AGAIN: 'User not found please register',
  REQUIRED_ALL_FIELD: 'Please required all field',
  PASSWORD_NOT_MATCH: 'Current password does not match',
  TYPE_INVALID: 'Invalid type',
  STATUS_INVALID: 'Invalid status value',
  DELETE: 'Data is successfully deleted',
};
export default messageUtil;
